---
# CentOS_install_epel-release/tasks/main.yml

- name: 'CentOS - install package epel-release'
  yum:
    name: 'epel-release'
    state: 'present'
  when: 'ansible_distribution == "CentOS"'
  notify:
    - "run 'yum makecache fast'"
    - "run 'dnf makecache'"

- name: 'CentOS - install epel-release key'
  rpm_key:
    key: '/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}'
    state: 'present'
  when: 'ansible_distribution == "CentOS"'
  ignore_errors: "{{ ansible_check_mode |default(false)}}"

- meta: flush_handlers
