---
# CentOS_install_epel-release/tasks/main.yml

- name: 'CentOS - install package epel-release'
  yum:
    name: 'epel-release'
    state: 'present'
  when: 'ansible_distribution == "CentOS"'
  notify:
    - 'CentOS - install epel-release key'
    - "run 'yum makecache fast'"
    - "run 'dnf makecache'"

- meta: flush_handlers
