---
# CentOS_install_epel-release/handlers/main.yml

- name: 'CentOS - install epel-release key'
  ansible.builtin.rpm_key:
    key: '/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}'
    state: 'present'
  when:
    - 'ansible_distribution == "CentOS"'

- name: "Run 'yum makecache fast'"
  ansible.builtin.command: "yum makecache fast"
  when:
    - 'ansible_distribution == "CentOS"'
    - 'ansible_distribution_major_version | int == 7'

- name: "Run 'dnf makecache'"
  ansible.builtin.command: "dnf makecache"
  when:
    - 'ansible_distribution == "CentOS"'
    - 'ansible_distribution_major_version | int == 8'
